### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ChristopherDurand** [ChristopherDurand/shopping_cart#2]
- [ ] Split up `AddToCart` function into multiple, smaller functions

- [ ] Implement Add to Cart button

- [ ] Prevent purchasing an item with 0 quantity

- [ ] Changing product price should update the price in the cart

- [ ] Change "Add a product" button on Edit form to "Submit Changes"
